const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addStaticLibrary(.{ .name = "ft", .target = target, .optimize = optimize });
    lib.addCSourceFiles(.{ .root = b.path("src"), .files = &.{ "ft_array/fta_alloc.c", "ft_array/fta_append.c", "ft_array/fta_clear.c", "ft_array/fta_clearf.c", "ft_array/fta_iter.c", "ft_array/fta_iteri.c", "ft_array/fta_new.c", "ft_array/fta_overwrite.c", "ft_array/fta_popback.c", "ft_array/fta_popindex.c", "ft_array/fta_release.c", "ft_array/fta_replace.c", "ft_array/fta_reserve.c", "ft_array/fta_resize.c", "ft_array/fta_string.c", "ft_array/fta_swap.c", "ft_array/fta_trim.c", "ft_atoi.c", "ft_bzero.c", "ft_ctype.c", "ft_deque/ft_deque.c", "ft_deque/ft_stack.c", "ft_deque/ft_stack_pushswap.c", "ft_deque/ftq_getters.c", "ft_deque/ftq_is_sorted.c", "ft_deque/ftq_iter.c", "ft_deque/ftq_pop.c", "ft_deque/ftq_private.c", "ft_deque/ftq_private_getters.c", "ft_deque/ftq_private_utils.c", "ft_deque/ftq_push.c", "ft_deque/ftq_string.c", "ft_dict.c", "ft_hashes.c", "ft_heap.c", "ft_itoa.c", "ft_itoa_base.c", "ft_list/ftl_add.c", "ft_list/ftl_del.c", "ft_list/ftl_new.c", "ft_list/ftl_pop.c", "ft_malloc.c", "ft_memalloc.c", "ft_memccpy.c", "ft_memchr.c", "ft_memcmp.c", "ft_memcpy.c", "ft_memdel.c", "ft_memdup.c", "ft_memmove.c", "ft_memset.c", "ft_memswp.c", "ft_modf.c", "ft_print_memory.c", "ft_printf/db_printf.c", "ft_printf/ft_convert.c", "ft_printf/ft_convert_characters.c", "ft_printf/ft_convert_extra.c", "ft_printf/ft_convert_integers.c", "ft_printf/ft_printf.c", "ft_printf/ft_string_vprintf.c", "ft_printf/ft_vasprintf.c", "ft_printf/ft_vprintf.c", "ft_printf/string_append_format.c", "ft_putchar.c", "ft_putchar_fd.c", "ft_putendl.c", "ft_putendl_fd.c", "ft_putnbr.c", "ft_putnbr_fd.c", "ft_putstr.c", "ft_putstr_fd.c", "ft_raii.c", "ft_realloc.c", "ft_string.c", "ft_string_legacy/ft_strcat.c", "ft_string_legacy/ft_strchr.c", "ft_string_legacy/ft_strclr.c", "ft_string_legacy/ft_strcmp.c", "ft_string_legacy/ft_strcpy.c", "ft_string_legacy/ft_strdel.c", "ft_string_legacy/ft_strdup.c", "ft_string_legacy/ft_strequ.c", "ft_string_legacy/ft_striter.c", "ft_string_legacy/ft_striteri.c", "ft_string_legacy/ft_strjoin.c", "ft_string_legacy/ft_strlcat.c", "ft_string_legacy/ft_strlen.c", "ft_string_legacy/ft_strmap.c", "ft_string_legacy/ft_strmapi.c", "ft_string_legacy/ft_strncat.c", "ft_string_legacy/ft_strncmp.c", "ft_string_legacy/ft_strncpy.c", "ft_string_legacy/ft_strnequ.c", "ft_string_legacy/ft_strnew.c", "ft_string_legacy/ft_strnstr.c", "ft_string_legacy/ft_strrchr.c", "ft_string_legacy/ft_strrev.c", "ft_string_legacy/ft_strsplit.c", "ft_string_legacy/ft_strstr.c", "ft_string_legacy/ft_strsub.c", "ft_string_legacy/ft_strtrim.c", "ft_string_legacy/wide_char.c", "ft_tree/ftt_clear.c", "ft_tree/ftt_debug.c", "ft_tree/ftt_push.c", "ft_variadic.c", "get_next_line.c", "is_refresh.c" } });
    lib.addIncludePath(b.path("include"));
    lib.installHeadersDirectory(b.path("include"), "libft", .{});
    b.installArtifact(lib);
}
