name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Download source files
        uses: actions/checkout@v3.0.0
      - name: Compile
        run: make -j
      - name: Compile test framework
        run: CPPFLAGS=-I../../include make -C test/framework
      - name: Generate tests
        run: ( cd test ; bash ./generate.sh )
      - name: Compile tests
        run: CPPFLAGS="-I ../include -I framework" LDFLAGS="-L .. -L framework" LDLIBS="-lunit -lft" make -j -C test
      - name: Run tests
        run: ./test/test_libft.exe

  use-conan:
    name: Create Conan package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Download source files
        uses: actions/checkout@v3.0.0
      - name: Setup Python
        uses: actions/setup-python@v3.0.0
      - name: Install conan
        run : python3 -m pip install conan
      - name: Compile libft
        run: |
          conan install .
          conan build .
          conan export-pkg .
      - name: Compile test framework
        run: ( cd test/framework ; conan export-pkg . )
      - name: Generate and compile tests
        run: ( cd test ; bash generate.sh ; conan install . --build --options="libft:shared=False" ; make -j )
      - name: Run tests
        run: ./test/test_libft.exe
