name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    name: Test on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc-12, clang]
        exclude:
          # GCC on macos is just clang in disguise
          - os: macos-latest
            compiler: gcc-12
    steps:
      - name: Download source files
        uses: actions/checkout@v3
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
      - name: Compile libft
        run: |
          ${{ matrix.compiler }} --version
          CC=${{ matrix.compiler }} make -j ${{ steps.cpu-cores.outputs.count }}
      - name: Compile test framework
        run: CC=${{ matrix.compiler }} CPPFLAGS="-I ../../include" make -C test/framework
      - name: Compile tests
        run: CC=${{ matrix.compiler }} CPPFLAGS="-I ../include -I framework" LDFLAGS="-L .. -L framework" LDLIBS="-lunit -lft" make -C test -j ${{ steps.cpu-cores.outputs.count }}
      - name: Run tests
        run: ./test/test_libft.exe

  use-conan:
    name: Create Conan package on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
        exclude:
          # GCC on macos is just clang in disguise
          - os: macos-latest
            compiler: gcc
    steps:
      - name: Download source files
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
      - name: Install conan
        run : |
          comp_ver=$(${{ matrix.compiler }} --version | head -1)
          echo $comp_ver
          python3 -m pip install 'conan<2.0'
          conan profile new default --detect
          conan profile update settings.compiler=$( [ "Apple" = $(cut -d' ' -f1 <<< $comp_ver) ] && echo apple-clang || echo ${{ matrix.compiler }}) default
          conan profile update settings.compiler.version=$(cut -d' ' -f 4 <<< $comp_ver | cut -d'.' -f1) default
          conan profile update options.libft:shared=False default
          conan profile update env.CC=${{ matrix.compiler }} default
      - name: Compile libft
        run: conan create .
      - name: Compile test framework
        run: conan create test/framework
      - name: Compile tests
        run: |
          pushd test
          conan install .
          CC=${{ matrix.compiler }} make -j ${{ steps.cpu-cores.outputs.count }}
      - name: Run tests
        run: ./test/test_libft.exe
