name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Download source files
      uses: actions/checkout@v2
    - name: Compile
      run: make -j
    - name: Generate tests
      run: ( cd test ; bash ./generate.sh )
    - name: Compile tests
      run: ( cd test ; make -j )
    - name: Run tests
      run: make test
    - name: Clean
      run: make fclean
