name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Download source files
        uses: actions/checkout@v2.4.0
      - name: Compile
        run: make -j
      - name: Compile test framework
        run: CPPFLAGS=-I../../include make -C test/framework
      - name: Generate tests
        run: ( cd test ; bash ./generate.sh )
      - name: Compile tests
        run: CPPFLAGS="-I ../include -I framework" LDFLAGS="-L .. -L framework" LDLIBS="-lunit -lft" make -j -C test
      - name: Run tests
        run: ./test/test_libft.exe
      - name: Clean
        run: make fclean && make -C test fclean && make -C test/framework fclean
  use-conan:
    name: Create Conan package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Download source files
        uses: actions/checkout@v2.4.0
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install conan
        run : |
          python3 -m venv localenv
          source localenv/bin/activate
          python -m pip install conan
          deactivate
      - name: Compile libft
        run: |
          source localenv/bin/activate
          conan install .
          conan build .
          conan package .
          conan export-pkg . --package-folder=package
          deactivate
      - name: Compile test framework
        run: |
          source localenv/bin/activate
          pushd test/framework
          conan install .
          conan build .
          conan package .
          conan export-pkg . --package-folder=package
          popd
          deactivate
      - name: Generate and compile tests
        run: |
          source localenv/bin/activate
          ( cd test ; bash generate.sh ; conan install . ; make -j )
          deactivate
      - name: Run tests
        run: |
          source test/activate_run.sh
          ./test/test_libft.exe
          source test/deactivate_run.sh
      - name: Clean
        run: git clean -xdf
