name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Download source files
        uses: actions/checkout@v2
      - name: Compile
        run: make -j
      - name: Generate tests
        run: ( cd test ; bash ./generate.sh )
      - name: Compile tests
        run: make -C test -j
      - name: Run tests
        run: ./test/test_libft.exe
      - name: Clean
        run: make fclean && make -C test fclean
  use-conan:
    name: Create Conan package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Download source files
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install conan
        run : |
          python3 -m venv localenv
          source localenv/bin/activate
          python -m pip install conan
          deactivate
      - name: Compile with conan
        run: |
          source localenv/bin/activate
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan install .
          conan build .
          conan package .
          deactivate
      - run: find package/
